name: Merge the upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 5'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        sparse-checkout: '.'
        ref: akirak

    - name: Switch to a work branch
      run: git switch -C upstream-recipes

    - name: Fetch the upstream
      run: |
        git remote add upstream https://github.com/melpa/melpa.git
        git fetch upstream master

    - uses: DeterminateSystems/nix-installer-action@v4
      with:
        diagnostic-endpoint: ''

    - name: Merge upstream recipes
      run: |
        # Set some identity. Actually it will be overridden later, so it's
        # unused
        git config --add user.name 'github-actions[bot]'
        git config --add user.email '6270544+github-actions[bot]@users.noreply.github.com'
        nix run github:emacs-twist/recipes-updater#forceUpdate \
          --no-write-lock-file -- upstream/master

    # A workaround to prevent peter-evans/create-pull-request from resetting the
    # head here:
    # <https://github.com/peter-evans/create-pull-request/blob/d806186ee3288c60a352af9852b6b18afbbfd87e/src/create-or-update-branch.ts#L178>
    - name: Detach the head
      run: git switch --detach `git rev-parse HEAD`

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v5
      with:
        base: akirak
        token: ${{ secrets.PAT_FOR_PR }}
        title: 'Merge the upstream recipe commits'
        branch: create-pull-request/merge-recipes
        labels: automation
