name: Merge the upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 3'

jobs:
  job:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        ref: akirak

    - name: Check out a new branch on the upstream master
      run: |
        git remote add upstream https://github.com/melpa/melpa.git
        git fetch upstream
        git switch -C upstream-recipes upstream/master

    - run: git merge-base --octopus HEAD akirak

    - name: Install Nix for installing git-filter-repo
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install git-filter-repo
      run: nix profile install nixpkgs#git-filter-repo

    - name: Get the base commit
      id: merge-base
      run: |
        base=$(git merge-base upstream/master origin/akirak)
        echo "BASE_COMMIT=$base" >> "$GITHUB_OUTPUT"

    - name: Rewrite the history
      run: |
        git filter-repo --path recipes/ \
          --refs "${{ steps.merge-base.outputs.BASE_COMMIT }}..HEAD"

    - name: Rebase
      run: git rebase akirak

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v5
      with:
        base: akirak
        token: ${{ secrets.PAT_FOR_PR }}
        title: 'Merge the upstream recipe commits'
        labels: automation
